#!/bin/sh

[ -z "$(dmesg | awk -F 'CPU:|MHz' '/Clocks:/{print $2+0}')" ] && sed -i '/><%:CPU Clock%></d' /usr/lib/lua/luci/view/admin_status/index.htm
[ -z "$(dmesg | awk -F 'DDR:|MHz' '/Clocks:/{print $3+0}')" ] && sed -i '/><%:RAM Clock%></d' /usr/lib/lua/luci/view/admin_status/index.htm

echo "net.ipv4.tcp_fastopen=3" > /etc/sysctl.d/30-tcp_fastopen.conf

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua

uci -q batch <<-EOF >/dev/null
	set luci.main.mediaurlbase=/luci-static/material
	commit luci
EOF

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache


ula_prefix="2fff:$(head -n 128 /dev/urandom | tr -dc '0123456789abcdef' | head -c4):$(head -n 128 /dev/urandom | tr -dc '0123456789abcdef' | head -c4)::/64"

uci -q batch <<-EOF >/dev/null
set dhcp.lan.ra='server'
set dhcp.lan.dhcpv6='server'
set dhcp.lan.ra_management='1'
set dhcp.lan.ra_default='1'
set dhcp.odhcpd.loglevel='3'
commit dhcp
set network.client.ra_holdoff='30'
set network.globals.ula_prefix="$ula_prefix"
commit network
EOF

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

addnhosts=$(uci -q get dhcp.@dnsmasq[0].addnhosts)
[ -z "$(echo $addnhosts | grep '/tmp/dnsmasq-lede.router')" ] && {
	uci add_list dhcp.@dnsmasq[0].addnhosts="/tmp/dnsmasq-lede.router"
	uci commit dhcp
}


#####################防止LAN与WAN网段重合#########################

lan_ip=$(uci -q get network.lan.ipaddr)

[ -n "$lan_ip" ] && {
	/etc/init.d/network restart

	for i in $(seq 1 10); do
		sleep 2
		wan_up=$(ubus call network.interface.wan status 2>/dev/null | grep '"up"' | grep "true")
		wan_ip=$(ubus call network.interface.wan status 2>/dev/null | grep \"address\" | grep -Eo '([^0-9]|\b)((1[0-9]{2}|2[0-4][0-9]|25[0-5]|[1-9][0-9]|[0-9])\.){3}(1[0-9][0-9]|2[0-4][0-9]|25[0-5]|[1-9][0-9]|[0-9])([^0-9]|\b)' | sed -nr 's/([^0-9]|\b)(([0-9]{1,3}\.){3}[0-9]{1,3})([^0-9]|\b)/\2/p')
		lan_up=$(ubus call network.interface.lan status 2>/dev/null | grep '"up"' | grep "true")
		[ -n "$wan_up" ] && [ -n "$lan_up" ] && [ -n "$wan_ip" ] && break
	done

	[ -n "$wan_up" ] && [ -n "$lan_up" ] && [ -n "$wan_ip" ] && {

		wan_ip1=$(echo $wan_ip | cut -d '.' -f1)
		wan_ip2=$(echo $wan_ip | cut -d '.' -f2)
		wan_ip3=$(echo $wan_ip | cut -d '.' -f3)

		lan_ip1=$(echo $lan_ip | cut -d '.' -f1)
		lan_ip2=$(echo $lan_ip | cut -d '.' -f2)
		lan_ip3=$(echo $lan_ip | cut -d '.' -f3)
		lan_ip4=$(echo $lan_ip | cut -d '.' -f4)

		[ $wan_ip1 -eq $lan_ip1 ] && [ $wan_ip2 -eq $lan_ip2 ] && [ $wan_ip3 -eq $lan_ip3 ] && {
			lan_ip3=$(expr $lan_ip3 + 1)
			lan_ip3=$(expr $lan_ip3 % 255)
			lan_ip=$lan_ip1.$lan_ip2.$lan_ip3.$lan_ip4
			uci set network.lan.ipaddr=$lan_ip
			uci commit network.lan.ipaddr
			/etc/init.d/network restart
		}		
	}
}
#####################防止LAN与WAN网段重合#########################

exit 0
